exclude: '.pre-commit-config.yaml$'
repos:
  - repo: local
    hooks:
      - id: black
        name: black linter for Python code
        language: python
        files: '\.py$'
        entry: black
        args: ['--exclude', '((static|venv)/|/tests?(\.py$)?)', '-l', '100']
        additional_dependencies: ['black']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
        name: flake8
        language: python